name: CI

on: [push, pull_request]

jobs:
  check-opam-sanity:
    name: Check sanity of opam/Satyristes
    runs-on: ubuntu-latest
    container:
      image: amutake/satysfi:0.0.5
    steps:
      - uses: actions/checkout@v1
      - name: Try install derive
        run: |
          export HOME=/root
          eval $(opam env)
          opam update
          opam pin add "file://${PWD}"
          satyrographos install -l derive
  regression-test:
    name: Regression tests
    runs-on: ubuntu-latest
    container:
      image: zeptometer/satysfi-yarn-diff-pdf:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Yarn dependencies
        run: yarn install
      - name: Install Satyrographos dependencies
        run: |
          export HOME=/root
          eval $(opam env)
          opam update
          opam pin add --verbose --yes "."
          satyrographos install -l derive
      - name: Run regression tests
        run: |
          export HOME=/root
          eval $(opam env)
          yarn test --ci
